### ISSUE TITLE
Remove katello as dependency in rubocop 

### ISSUE THREAD

**Issue by dosas** [theforeman/foreman_kernel_care#62]
This [line](https://github.com/theforeman/foreman_kernel_care/blob/master/.github/workflows/rubocop.yaml#L14) does not only remove `katello` for linting with rubocop it also removes `foreman_remote_execution`

The following should only remove katello
```
 sed -i "/s.add_dependency 'katello'/ s/^#*/#/" foreman_kernel_care.gemspec
```

Also is there an alternative option?

**Comment by maccelf** [comment]
Why do we need `foreman_remote_execution` for running `rubocop` ?

**Comment by dosas** [comment]
@maccelf I cannot answer that question. 

The problem I see is that the comment says: `Remove Katello from dependencies` but what it does is that it removes all `.add_dependencies`

So either the comment is wrong and needs to be adapted or the sed command is wrong and needs to be adapted.

**Comment by maccelf** [comment]
Okay, got it
